stages:
  preprocess:
    cmd: python src/process_dataset.py
    deps:
    - src/process_dataset.py
    - data/raw_dataset/train.csv
    - src/utils.py
    outs:
    - data/processed_dataset/train.csv
    - data/processed_dataset/test.csv
  hp_tune:
    # Set the hyperparameter tuning command
    cmd: python src/hp_tune.py
    params:
    - train.n_estimators
    - train.max_depth
    deps:
    - data/processed_dataset/train.csv
    # Specify the hyperparameter script as dependency
    - src/hp_tune.py
    - src/utils.py
    outs:
    - optimized_outputs/hp_tuning_results.md:
        cache: false # track by git, not dvc
    - optimized_outputs/rfc_best_params.json:
        cache: false # track by git, not dvc
  train:
    cmd: python src/train.py
    deps:
      - src/metrics_and_plots.py
      - src/model.py
      - data/processed_dataset/train.csv
      - data/processed_dataset/test.csv
      - optimized_outputs/rfc_best_params.json
      - src/train.py
      - src/utils.py
    metrics:
      - metrics.json:
          cache: false
    plots:
      - predictions.csv:
          template: confusion
          x: predicted_label
          y: true_label
          x_label: 'Predicted label'
          y_label: 'True label'
          title: Confusion matrix
          cache: false
      - roc_curve.csv:
          template: simple
          x: fpr
          y: tpr
          x_label: 'False Positive Rate'
          y_label: 'True Positive Rate'
          title: ROC curve
          cache: false